# Generated by Django 6.0.7 on 2026-07-28 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registereddevice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='students_departm_bebd12_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['semester'], name='students_semeste_0882c1_idx'),
        ),
        migrations.AddIndex(
            model_name='registereddevice',
            index=models.Index(fields=['student'], name='registered__student_eff85e_idx'),
        ),
    ]
