# Generated by Django 6.0.7 on 2026-07-28 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(max_length=500)),
                ('qr_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='courses.lecture')),
            ],
            options={
                'db_table': 'qr_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lecture'], name='qr_sessions_lecture_ccf54e_idx'), models.Index(fields=['expires_at'], name='qr_sessions_expires_295205_idx'), models.Index(fields=['is_active'], name='qr_sessions_is_acti_e53aa3_idx')],
            },
        ),
    ]
