# Generated by Django 6.0.7 on 2026-07-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestatistics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='attendancestatistics',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_statistics'),
        ),
    ]
