# Generated by Django 6.0.7 on 2026-07-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='courses_teacher_e891c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='courses_semeste_1995ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_enrollment'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['course'], name='lectures_course__c6f160_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['teacher'], name='lectures_teacher_f8e838_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['lecture_date'], name='lectures_lecture_b907d7_idx'),
        ),
    ]
