# Generated by Django 6.0.7 on 2026-07-28 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20)),
                ('verification_method', models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual', 'Manual')], max_length=20)),
                ('marked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-marked_at'],
            },
        ),
    ]
